// lib/features/todo/data/model/todo_model.dart
import 'package:hive/hive.dart';
import 'package:provider_todo/features/todo/domain/entities/todo_entity.dart';

part 'todo_model.g.dart';   // generated by build_runner

@HiveType(typeId: 0)
class TodoModel extends TodoEntity {
  @HiveField(0)
  final String hiveId;
  @HiveField(1)
  final String hiveTitle;
  @HiveField(2)
  final String hiveDescription;
  @HiveField(3)
  final DateTime hiveCreatedAt;
  @HiveField(4)
  final bool hiveIsCompleted;

  const TodoModel({
    required String id,
    required String title,
    required String description,
    required DateTime createdAt,
    bool isCompleted = false,
  })  : hiveId = id,
        hiveTitle = title,
        hiveDescription = description,
        hiveCreatedAt = createdAt,
        hiveIsCompleted = isCompleted,
        super(
          id: id,
          title: title,
          description: description,
          createdAt: createdAt,
          isCompleted: isCompleted,
        );

  factory TodoModel.fromEntity(TodoEntity entity) => TodoModel(
        id: entity.id,
        title: entity.title,
        description: entity.description,
        createdAt: entity.createdAt,
        isCompleted: entity.isCompleted,
      );

  // Supabase — fromJson / toJson
  factory TodoModel.fromJson(Map<String, dynamic> json) => TodoModel(
        id: json['id'],
        title: json['title'],
        description: json['description'],
        createdAt: DateTime.parse(json['created_at']),
        isCompleted: json['is_completed'] ?? false,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'title': title,
        'description': description,
        'created_at': createdAt.toIso8601String(),
        'is_completed': isCompleted,
      };

  @override
  TodoModel copyWith({
    String? id,
    String? title,
    String? description,
    DateTime? createdAt,
    bool? isCompleted,
  }) =>
      TodoModel(
        id: id ?? this.id,
        title: title ?? this.title,
        description: description ?? this.description,
        createdAt: createdAt ?? this.createdAt,
        isCompleted: isCompleted ?? this.isCompleted,
      );
}